### ISSUE TITLE
Help to use these APIs in an Alexa skill

### ISSUE THREAD

**Issue by jojo3632** [jeffkowalski/sunpower#2]
Hi,

This looks great.
Can anyone help with the creation of an Alexa skill to return the current solar electricity production?

Jordan.

**Comment by alex27riva** [comment]
Hi, I'm Italian and I want to do a skill for alexa too!

**Comment by jeffkowalski** [comment]
@alex27riva, you might look into doing something similar to what I've done in my "jen" skill, here: https://github.com/jeffkowalski/jen
